# Generated by Django 3.2.4 on 2021-07-05 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroId', models.IntegerField()),
                ('foto', models.ImageField(upload_to='')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=12)),
                ('direccion', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=100)),
                ('clave', models.CharField(max_length=15)),
                ('moneda', models.CharField(max_length=100)),
            ],
        ),
    ]
