# Generated by Django 3.2.4 on 2021-07-06 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='moneda',
            field=models.IntegerField(choices=[[0, 'Pesos'], [1, 'Dolares']]),
        ),
    ]
