# Generated by Django 3.2.4 on 2021-07-06 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_formulario_moneda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulario',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='numeroId',
        ),
    ]
